version: "3.7"
services:

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
    restart: unless-stopped

  # APP*****************************************
  springbootapp:
    image: my-spring:latest
    container_name: springbootapp
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgresdb
    links:
      - postgresdb
volumes:
  postgres-data: