version: "3.7"

services:

  react:
    container_name: react-dockerize
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  springboot:
    build:
      context: ../../../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
